import {test,expect} from '@playwright/test';
const games=[{slug:'orbit-ribbon',root:'#game',sound:'#sound',start:'Start stage 1',pause:'#pause',resume:'Resume'}, {slug:'amber-step',root:'#game',sound:'#sound',start:'Start stage 1',pause:'#pause',resume:'Resume'},{slug:'pulse-drift',root:'#pulse',sound:'#sound',start:'Launch',pause:'#pause',resume:'Resume'},{slug:'tilttrail',root:'#tilttrail',sound:'#tt-sound',start:'Play this stage',pause:'#tt-pause',resume:'Resume'}];
for(const game of games)test(`${game.slug}: audio gesture, individual settings, migration, save and pause`,async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/games/'+game.slug+'/?lang=en');await expect(page.locator(game.sound)).toHaveText('Sound OFF');await expect(page.locator(game.root)).toHaveAttribute('data-audio','off');
 await page.locator(game.sound).click();await expect(page.locator(game.sound)).toHaveText('Sound ON');await page.getByRole('button',{name:game.start,exact:true}).click();await page.locator(game.pause).click();await expect(page.locator(game.root)).toHaveAttribute('data-audio','running');await expect(page.locator(game.root)).toHaveAttribute('data-audio-samples','9');
 await page.getByRole('button',{name:'Volume settings',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(page.locator(game.root)).toHaveAttribute('data-audio-loops','0');
 await dialog.getByRole('slider',{name:'Music',exact:true}).fill('35');await dialog.getByRole('slider',{name:'Effects',exact:true}).fill('70');await dialog.getByRole('button',{name:'Mute',exact:true}).first().click();await expect(dialog.getByRole('button',{name:'Unmute',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('audio-320.png')});
 const key=game.slug==='orbit-ribbon'?'orbit':game.slug==='amber-step'?'amber':game.slug==='pulse-drift'?'pulse':'tilt';const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem('pocketey-audio-v1')!)[k],key);expect(saved).toEqual({music:.35,sfx:.7,musicMuted:true,sfxMuted:false});
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:game.resume,exact:true}).last().click();await page.waitForTimeout(350);await page.locator(game.pause).click();await expect(page.locator(game.root)).toHaveAttribute('data-audio-loops','0');await page.reload();await expect(page.locator(game.sound)).toHaveText('Sound ON');await page.getByRole('button',{name:'Volume settings',exact:true}).click();await expect(page.getByRole('slider',{name:'Music',exact:true})).toHaveValue('35');await expect(page.getByRole('slider',{name:'Effects',exact:true})).toHaveValue('70');expect(errors).toEqual([]);
});
for(const game of games)test(`${game.slug}: unavailable audio does not stop play`,async({page})=>{
 await page.route('**/games/audio/**',r=>r.abort());await page.addInitScript(()=>{const original=AudioContext.prototype.resume;AudioContext.prototype.resume=function(){void original.call(this).catch(()=>{});return Promise.reject(new Error('test resume refusal'));};});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/games/'+game.slug+'/?lang=en');await page.locator(game.sound).click();await page.getByRole('button',{name:game.start,exact:true}).click();await page.waitForTimeout(400);await expect(page.locator(game.pause)).toBeEnabled();await page.locator(game.pause).click();await expect(page.getByRole('button',{name:game.resume,exact:true}).last()).toBeVisible();expect(errors).toEqual([]);
});
test('legacy enabled flags migrate without clearing any game progress',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('pocketey-orbit-amber-v1',JSON.stringify({version:1,sound:true,orbit:{unlocked:3,best:[11,12,13]},amber:{unlocked:3,best:[14,15,16]}}));localStorage.setItem('pocketey-pulse-drift-v1',JSON.stringify({mute:false,best:[100,200,300]}));localStorage.setItem('pocketey-tilttrail-v1',JSON.stringify({muted:false,best:[11,12,13]}));});
 for(const game of games){await page.goto('/games/'+game.slug+'/?lang=en');await expect(page.locator(game.sound)).toHaveText('Sound ON');}
 const legacy=await page.evaluate(()=>JSON.parse(localStorage.getItem('pocketey-orbit-amber-v1')!));expect(legacy.orbit.best).toEqual([11,12,13]);expect(legacy.amber.best).toEqual([14,15,16]);
});
for(const game of games)test(`${game.slug}: hidden lifecycle releases audio and requires explicit resume`,async({page})=>{
 await page.goto('/games/'+game.slug+'/?lang=en');await page.locator(game.sound).click();await page.getByRole('button',{name:game.start,exact:true}).click();await expect(page.locator(game.root)).toHaveAttribute('data-audio','running');
 // Browser-lifecycle simulation only: no game state or physics is modified.
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.locator(game.root)).toHaveAttribute('data-audio','suspended');await expect(page.locator(game.root)).toHaveAttribute('data-audio-loops','0');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByRole('button',{name:game.resume,exact:true}).last()).toBeVisible();await page.getByRole('button',{name:game.resume,exact:true}).last().click();await expect(page.locator(game.root)).toHaveAttribute('data-audio','running');
});
for(const game of games.slice(2))test(`${game.slug}: ordinary keyboard movement, input release and translated pause`,async({page})=>{
 await page.goto('/games/'+game.slug+'/?lang=en');await page.getByRole('button',{name:game.start,exact:true}).click();
 const x=()=>page.locator(game.root).evaluate(e=>e.id==='pulse'?JSON.parse((e as HTMLElement).dataset.state!).x:Number((e as HTMLElement).dataset.x));const before=await x();await page.keyboard.down('ArrowRight');await page.waitForTimeout(300);await page.keyboard.up('ArrowRight');expect(await x()).toBeGreaterThan(before);
 await page.locator(game.pause).click();await expect(page.locator(game.root)).toHaveAttribute(game.slug==='pulse-drift'?'data-mode':'data-phase',game.slug==='pulse-drift'?'pause':'paused');const frozen=await x();await page.waitForTimeout(200);expect(await x()).toBe(frozen);await page.getByRole('button',{name:'日本語',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.getByRole('button',{name:'再開',exact:true}).last()).toBeVisible();await page.getByRole('button',{name:'再開',exact:true}).last().click();await expect(page.locator(game.pause)).toBeEnabled();
});
for(const game of games)test(`${game.slug}: volume dialog blocks game keys and pointers; close keeps pause`,async({page})=>{
 await page.goto('/games/'+game.slug+'/?lang=en');await page.getByRole('button',{name:game.start,exact:true}).click();
 const phase=()=>expect(page.locator(game.root)).toHaveAttribute(game.slug==='tilttrail'?'data-phase':'data-mode',game.slug==='tilttrail'?'paused':'pause');
 const snapshot=()=>page.locator(game.root).evaluate(e=>{const d=(e as HTMLElement).dataset;if(e.id==='pulse'){const s=JSON.parse(d.state!);return{time:s.time,x:s.x,y:s.y,hp:s.hp};}return{time:d.time??document.querySelector('#timer')?.textContent,x:d.x,y:d.y,z:d.z,jumps:d.jumps,vx:d.vx};});
 await page.keyboard.down('ArrowRight');await page.getByRole('button',{name:'Volume settings',exact:true}).click();await phase();await page.keyboard.up('ArrowRight');await expect(page.getByRole('dialog')).toBeVisible();expect(await page.locator(game.root).evaluate(e=>(e as HTMLElement).inert)).toBe(true);
 const frozen=await snapshot();
 for(const key of ['r','p','Space','ArrowRight'])await page.keyboard.press(key);
 await page.mouse.move(3,550);await page.mouse.down();await page.mouse.move(8,540);await page.mouse.up();await page.waitForTimeout(200);await phase();expect(await snapshot()).toEqual(frozen);await expect(page.getByRole('dialog')).toBeVisible();
 // Range keys retain their native setting behavior without reaching game controls.
 const range=page.getByRole('slider',{name:'Effects',exact:true});await range.focus();await page.keyboard.press('ArrowLeft');await expect(range).toHaveValue('75');await phase();
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await phase();expect(await snapshot()).toEqual(frozen);expect(await page.locator(game.root).evaluate(e=>(e as HTMLElement).inert)).toBe(false);
 // Opening an already-paused game and closing with movement keys held never resumes it.
 await page.getByRole('button',{name:'Volume settings',exact:true}).click();await page.keyboard.down('ArrowRight');await page.keyboard.down('Space');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await phase();await page.waitForTimeout(150);expect(await snapshot()).toEqual(frozen);
 await page.getByRole('button',{name:game.resume,exact:true}).last().click();const resumed=await snapshot();await page.keyboard.down('ArrowRight');await page.keyboard.down('Space');await page.waitForTimeout(200);const after=await snapshot();if(game.slug==='orbit-ribbon')expect(after.z).toBe(resumed.z);else if(game.slug==='tilttrail')expect(Math.abs(Number(after.vx))).toBeLessThanOrEqual(Math.abs(Number(resumed.vx))+.001);else expect(after.x).toBe(resumed.x);if(game.slug==='orbit-ribbon'||game.slug==='amber-step')expect(after.jumps).toBe(resumed.jumps);
 await page.keyboard.up('ArrowRight');await page.keyboard.up('Space');await page.locator(game.pause).click();await phase();
});
