import {chromium,type Page} from '@playwright/test';
import {stages,SAVE_KEY,type Kind} from '../../../../src/games/model.ts';
import fs from 'node:fs';
const out='/workspace/pocketey-portal/docs/games/evidence/difficulty-refresh';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const results:any[]=[];
async function freeze(page:Page){await page.evaluate(()=>{(window as any).freezeFrame=true});await page.waitForFunction(()=>!!(window as any).pendingFrame,null,{polling:50});}
async function resume(page:Page){await page.evaluate(()=>{(window as any).freezeFrame=false;const next=(window as any).pendingFrame;(window as any).pendingFrame=null;next(performance.now())});}
try{for(const kind of ['orbit','amber'] as Kind[])for(const width of [390,1280])for(const checkpoint of (kind==='orbit'?[{x:20.7,name:'switch-and-gap'},{x:54.2,name:'long-gap-airborne'}]:[{x:17.7,name:'edge-spike-and-downhill-gap'},{x:21,name:'combined-jump-airborne'}])){
 const context=await browser.newContext({locale:'ja-JP',viewport:{width,height:width===390?844:720},deviceScaleFactor:1,isMobile:width===390,hasTouch:width===390});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Shader Error/.test(m.text()))errors.push(m.text())});
 await page.addInitScript(key=>{localStorage.setItem(key,JSON.stringify({version:1,sound:false,orbit:{unlocked:3,best:[13,16,18]},amber:{unlocked:3,best:[10,12,14]}}));const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=callback=>raf(now=>{if((window as any).freezeFrame)(window as any).pendingFrame=callback;else callback(now)});},SAVE_KEY);
 await page.goto(`http://127.0.0.1:4322/games/${kind==='orbit'?'orbit-ribbon':'amber-step'}/?lang=ja`);await page.waitForFunction(()=>document.querySelector<HTMLCanvasElement>('canvas')?.dataset.artAdopted==='true');
 await page.getByRole('button',{name:/ステージ 3 /}).click();await page.getByRole('button',{name:'ステージ 3 をはじめる'}).click();
 const session=width===390?await context.newCDPSession(page):null;const held=new Set<string>();const points:Record<string,any>={};for(const [id,name] of ['left','right','jump'].entries()){const b=await page.locator(`[data-input=${name}]`).boundingBox();points[name]={id:id+1,x:b!.x+b!.width/2,y:b!.y+b!.height/2};}const keys:Record<string,string>={left:'ArrowLeft',right:'ArrowRight',jump:'Space'};
 async function input(names:string[]){if(session){const removed=[...held].filter(n=>!names.includes(n)),added=names.filter(n=>!held.has(n));if(removed.length)await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:removed.map(n=>points[n])});if(added.length)await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:names.map(n=>points[n])});}else{for(const n of held)if(!names.includes(n))await page.keyboard.up(keys[n]);for(const n of names)if(!held.has(n))await page.keyboard.down(keys[n]);}held.clear();names.forEach(n=>held.add(n));}
 const checkpoints=[checkpoint];let captured=0,lastJump=-10;const trace:any[]=[];const start=Date.now(),level=stages[kind][2];
 while(Date.now()-start<50000 && captured<checkpoints.length){
  const d=await page.locator('#game').evaluate(e=>({... (e as HTMLElement).dataset}));if(d.status!=='running')throw Error(`${kind}/${width}: ${JSON.stringify(d)}`);const x=Number(d.x),z=Number(d.z),time=x/(kind==='orbit'?7:5),tile=level.platforms.find(p=>x>=p.a-.23&&x<=p.b+.23);
  const gap=!!tile&&tile.b<level.length&&tile.b-x<(kind==='orbit'?1.1:1)&&tile.b-x>-.15;
  const spike=kind==='amber'&&level.hazards.some(h=>h.x-x<(tile&&tile.b-h.x<.9?1.35:1.65)&&h.x-x>0);
  let axis=1;if(kind==='orbit'){const h=level.hazards.find(h=>h.x+h.d/2+.3>x),target=h&&h.x-x<12?(h.z>=0?-1.85:1.85):0;axis=Math.abs(target-z)<.18?0:Math.sign(target-z);}
  const jump=(gap||spike)&&d.grounded==='true'&&time-lastJump>.3;if(jump)lastJump=time;const names:string[]=[];if(axis)names.push(axis>0?'right':'left');if(jump)names.push('jump');await input(names);trace.push({state:d,names});
  if(x>=checkpoints[captured].x){await freeze(page);if(!await page.locator('#overlay').isHidden())throw Error('overlay');await page.screenshot({path:`${out}/${kind}-${width}-${checkpoints[captured].name}.png`});results.push({kind,width,scene:checkpoints[captured].name,state:await page.locator('#game').evaluate(e=>({... (e as HTMLElement).dataset})),canvas:await page.locator('canvas').evaluate(e=>({width:(e as HTMLCanvasElement).width,height:(e as HTMLCanvasElement).height})),errors});captured++;if(captured<checkpoints.length)await resume(page);}
  await page.waitForTimeout(25);
 }
 if(captured!==checkpoints.length)throw Error('Capture timeout');fs.writeFileSync(`${out}/${kind}-${width}-${checkpoint.name}-input-trace.json`,JSON.stringify(trace));await input([]);await context.close();
}fs.writeFileSync(`${out}/capture.json`,JSON.stringify({method:'Native stage selection from preserved legacy unlocked-3 fixture, then normal keyboard/CDP two-finger input from x=0. Each image has its own run from x=0; rAF is held only for the final screenshot and play is not resumed after it, with no physics-state writes. These views show visibility and combinations; automated route completion is checked separately and does not establish human difficulty.',results},null,2));}finally{await browser.close()}
