import {test,expect,type Page} from '@playwright/test';import fs from 'node:fs';
const key='pocketey-conveyor-campaign-v3',oldKey='pocketey-conveyor-campaign-v2';
const prior={version:2,active:'read-the-inlet',legacyImported:false,records:{'first-dispatch':{rotations:[0,0],turns:2,best:2},'factory-loop':{rotations:[0,0,0,1,1,2,2,3],turns:7,best:7},'read-the-inlet':{rotations:[1,1,2,2,3,3,0,1],turns:6,best:6}}};
async function seed(page:Page,value:any=prior){await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(value));},{key:oldKey,value});await page.goto('/prototypes/conveyor/?lang=en');await expect(page.locator('#conveyor')).toHaveAttribute('data-render-pending','false');}
async function openChoice(page:Page){await page.locator('button[data-mission="choose-a-route"]').tap();await expect(page.locator('#conveyor')).toHaveAttribute('data-mission','choose-a-route');await expect(page.locator('#conveyor')).toHaveAttribute('data-render-pending','false');}
async function rotate(page:Page,route:'upper'|'lower') {
 const steps: [string,number][] = route==='upper' ? [['a',2],['f',3]] : [['a',1],['d',1],['e',1]];
 for(const [id,n] of steps) for(let i=0;i<n;i++) await page.locator(`button[data-tile="${id}"]`).tap();
}
async function budget(page:Page){await expect(page.locator('#conveyor')).toHaveAttribute('data-render-pending','false');const d=await page.locator('#conveyor').evaluate(el=>({...((el as HTMLElement).dataset)}));expect(Number(d.drawCalls)).toBeLessThanOrEqual(90);expect(Number(d.triangles)).toBeLessThanOrEqual(15000);return d;}
test('v2 imports unchanged; upper5 and lower3 both deliver through ordinary taps and keep independent records',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await seed(page);const old=await page.evaluate(key=>localStorage.getItem(key),oldKey);await openChoice(page);await expect(page.locator('#cv-intro')).toContainText('optional');
 await page.screenshot({path:info.outputPath('choice-start-390.png'),fullPage:true});const routes=[];
 for(const route of['upper','lower']as const){if(route==='lower')await page.locator('#cv-reset').tap();await rotate(page,route);await page.screenshot({path:info.outputPath(`${route}-planned-390.png`),fullPage:true});await page.locator('#cv-play').tap();await expect.poll(async()=>Number(await page.locator('#conveyor').getAttribute('data-elapsed')),{intervals:[25]}).toBeGreaterThan(1.15);await page.locator('#cv-play').tap();await expect(page.locator('#conveyor')).toHaveAttribute('data-phase','paused');const mid=await budget(page);await page.screenshot({path:info.outputPath(`${route}-parcel-390.png`),fullPage:true});await page.locator('#cv-play').tap();await expect(page.locator('#conveyor')).toHaveAttribute('data-phase','success');await expect(page.locator('#cv-turns')).toHaveText(`${route==='upper'?5:3} turns`);await expect(page.locator('#cv-target')).toHaveAttribute('data-earned',String(route==='lower'));await page.screenshot({path:info.outputPath(`${route}-delivered-390.png`),fullPage:true});routes.push({route,mid,final:await budget(page)});}
 const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key);for(const id of Object.keys(prior.records))expect(saved.records[id]).toEqual(prior.records[id as keyof typeof prior.records]);expect(saved.records['choose-a-route'].best).toBe(3);expect(saved.version).toBe(3);expect(await page.evaluate(key=>localStorage.getItem(key),oldKey)).toBe(old);expect(await page.evaluate(()=>localStorage.getItem('pocketey-conveyor-v1'))).toBeNull();await page.reload();await expect(page.locator('#conveyor')).toHaveAttribute('data-mission','choose-a-route');await expect(page.locator('#cv-best')).toHaveText('Best: 3 turns');expect(errors).toEqual([]);fs.writeFileSync(info.outputPath('routes.json'),JSON.stringify({source:process.env.SOURCE_SHA,routes,saved,oldPreserved:true,errors},null,2));
});
test('two-way markings,44px targets and both languages remain readable at320x568 and844x390',async({page},info)=>{
 await page.emulateMedia({reducedMotion:'reduce'});await seed(page);await openChoice(page);
 for(const viewport of[{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(viewport);for(const lang of['ja','en']){await page.locator(`[data-language="${lang}"]`).tap();await page.locator('#cv-board').scrollIntoViewIfNeeded();await budget(page);const board=(await page.locator('#cv-board').boundingBox())!;expect(board.y).toBeGreaterThanOrEqual(0);expect(board.y+board.height).toBeLessThanOrEqual(viewport.height);const boxes=await page.locator('.cv-tile').evaluateAll(items=>items.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}));for(const b of boxes){expect(b.w).toBeGreaterThanOrEqual(44);expect(b.h).toBeGreaterThanOrEqual(44);expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.w).toBeLessThanOrEqual(viewport.width);}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(Math.min(a.x+a.w,b.x+b.w)<=Math.max(a.x,b.x)||Math.min(a.y+a.h,b.y+b.h)<=Math.max(a.y,b.y)).toBe(true);}await expect(page.locator('button[data-tile="a"]')).toHaveAttribute('aria-label',lang==='ja'?/両方向/:/two-way/);await page.screenshot({path:info.outputPath(`choice-${viewport.width}-${lang}.png`),fullPage:false});}}
 await page.locator('button[data-tile="a"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#cv-turns')).toHaveText('1 turns');
});
test('future saves appearing after boot stay untouched and another tab cannot lose its better record',async({page})=>{
 const older=structuredClone(prior);older.records['first-dispatch'].best=6;await seed(page,older);await openChoice(page);await page.locator('button[data-tile="a"]').tap();await page.evaluate(key=>{const save=JSON.parse(localStorage.getItem(key)!);save.records['first-dispatch']={rotations:[2,3],turns:11,best:2};localStorage.setItem(key,JSON.stringify(save));},key);await page.locator('button[data-tile="d"]').tap();let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key);expect(saved.records['first-dispatch']).toEqual({rotations:[2,3],turns:11,best:2});
 await page.evaluate(key=>localStorage.setItem(key,'{"version":99,"future":"untouched"}'),key);await page.locator('button[data-tile="e"]').tap();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe('{"version":99,"future":"untouched"}');await expect(page.locator('#cv-save')).toContainText('unavailable');
});
test('legacy completion of mission2 never grants an unearned fourth mission',async({page})=>{
 const incomplete=structuredClone(prior);incomplete.records['read-the-inlet'].best=null as any;await seed(page,incomplete);await expect(page.locator('button[data-mission="choose-a-route"]')).toBeDisabled();await page.locator('button[data-mission="choose-a-route"]').dispatchEvent('click');await expect(page.locator('#conveyor')).toHaveAttribute('data-mission','read-the-inlet');
});
