import {chromium} from '@playwright/test';import fs from 'node:fs/promises';
await fs.mkdir('test-results/shooter',{recursive:true});
const launch=()=>chromium.launch({executablePath:process.env.PULSE_BROWSER||(process.env.CI?undefined:'/usr/bin/chromium'),args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const report=[];
async function play(kind){const browser=await launch();const context=await browser.newContext({viewport:kind==='touch'?{width:390,height:844}:{width:1280,height:900},hasTouch:kind==='touch',isMobile:kind==='touch',deviceScaleFactor:1});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://localhost:4331/games/pulse-drift/?lang=${kind==='touch'?'ja':'en'}`);await page.waitForFunction(()=>document.querySelector('#pulse').dataset.mode==='menu');await page.locator('#sound').click();const cdp=await context.newCDPSession(page);let held=null;
 for(let stage=0;stage<3;stage++){if(stage){await page.getByRole('button',{name:kind==='touch'?'ステージ選択':'Stage select',exact:true}).last().click();}await page.getByRole('button',{name:kind==='touch'?`ステージ ${stage+1}`:`Stage ${stage+1}`,exact:true}).click();await page.getByRole('button',{name:kind==='touch'?'出撃する':'Launch',exact:true}).click();await page.waitForTimeout(200);let initial=JSON.parse(await page.locator('#pulse').getAttribute('data-state'));const rect=await page.locator('#field').boundingBox();const center=rect.x+rect.width/2;const a=initial.limits[0],b=initial.limits[1];const f=(initial.screen.y-b.y)/(a.y-b.y);const ppu=((center-a.x)*f+(b.x-center)*(1-f))/3.8;const ty=initial.screen.y;
 if(kind==='touch')await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:center,y:ty,id:1}]});let minHp=4,maxCalls=0,maxTriangles=0,inputs=0,start=Date.now();
 while(Date.now()-start<75000){const mode=await page.locator('#pulse').getAttribute('data-mode'),s=JSON.parse(await page.locator('#pulse').getAttribute('data-state'));minHp=Math.min(minHp,s.hp);maxCalls=Math.max(maxCalls,s.render.calls);maxTriangles=Math.max(maxTriangles,s.render.triangles);if(mode!=='play')break;
 const boss=s.enemies.find(e=>e.kind==='boss');const enemy=boss||s.enemies.filter(e=>e.y>3).sort((a,b)=>a.y-b.y)[0];const aim=enemy?enemy.x:0;let best=s.x,cost=Infinity;
 for(let x=-3.5;x<=3.5;x+=.25){let value=Math.abs(x-aim)*.5+Math.abs(x-s.x)*.22;for(const bullet of s.bullets){const time=(1.8-bullet.y)/bullet.vy;if(time>=-.12&&time<1.5){const bx=bullet.x+bullet.vx*Math.max(time,0);const dist=Math.abs(x-bx);value+=Math.exp(-dist*dist/.3)*8*(1.6-Math.max(time,0));}if(Math.hypot(x-bullet.x,1.8-bullet.y)<.55)value+=20;}for(const beam of s.beams){if(beam.age>.25&&beam.age<1.85&&Math.abs(x-beam.x)<.7)value+=20;}if(value<cost){cost=value;best=x;}}
 if(kind==='touch'){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:Math.max(rect.x+5,Math.min(rect.x+rect.width-5,center+best*ppu)),y:ty,id:1}]});inputs++;}else{const key=Math.abs(best-s.x)>.13?(best>s.x?'ArrowRight':'ArrowLeft'):null;if(key!==held){if(held)await page.keyboard.up(held);if(key)await page.keyboard.down(key);held=key;inputs++;}}
 if(s.time>9&&s.time<9.3)await page.screenshot({path:`test-results/shooter/${kind}-stage${stage+1}-play.png`});if(boss&&s.time>33&&s.time<33.4)await page.screenshot({path:`test-results/shooter/${kind}-boss.png`});await page.waitForTimeout(100);}
 if(kind==='touch')await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else if(held){await page.keyboard.up(held);held=null;}await page.waitForTimeout(150);const final=JSON.parse(await page.locator('#pulse').getAttribute('data-state'));await page.screenshot({path:`test-results/shooter/${kind}-stage${stage+1}-result.png`});report.push({kind,stage:stage+1,final,minHp,inputs,elapsedMs:Date.now()-start,maxCalls,maxTriangles,errors});console.log(kind,stage+1,final.status,final.hp,final.time,final.score);}
 await context.close();await browser.close();}
await play('touch');await play('keyboard');await fs.writeFile('test-results/shooter/play-report.json',JSON.stringify(report,null,2));if(report.some(r=>r.final.status!=='won'||r.errors.length))process.exitCode=1;
