import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
await fs.mkdir('test-results/shooter',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.PULSE_BROWSER||(process.env.CI?undefined:'/usr/bin/chromium'),args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report=[];
const state=async p=>JSON.parse(await p.locator('#pulse').getAttribute('data-state'));const open=async (p,lang='en')=>{await p.goto(`http://localhost:4331/games/pulse-drift/?lang=${lang}`);await p.waitForFunction(()=>document.querySelector('#pulse').dataset.mode==='menu');};
for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390},{width:1280,height:900}]){const context=await browser.newContext({viewport:size,hasTouch:true,isMobile:size.width<900});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page);for(const lang of ['ja','en']){await page.getByRole('button',{name:lang==='ja'?'日本語':'English',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const launch=page.getByRole('button',{name:lang==='ja'?'出撃する':'Launch',exact:true});await launch.scrollIntoViewIfNeeded();const rect=await launch.boundingBox();assert.ok(rect.y>=0&&rect.y+rect.height<=size.height+1);await page.screenshot({path:`test-results/shooter/layout-${size.width}-${lang}.png`});}
await page.getByRole('button',{name:'Launch',exact:true}).click();await page.keyboard.down('ArrowRight');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');await page.waitForTimeout(350);const stopped=(await state(page)).x;await page.waitForTimeout(200);assert.ok(Math.abs((await state(page)).x-stopped)<.01,'keyboard released');
await page.keyboard.down('ArrowUp');await page.waitForTimeout(250);await page.keyboard.up('ArrowUp');await page.waitForTimeout(350);const forward=(await state(page)).y;assert.ok(forward>1.8);await page.keyboard.down('ArrowDown');await page.waitForTimeout(250);await page.keyboard.up('ArrowDown');await page.waitForTimeout(350);assert.ok((await state(page)).y<forward);const touchY=(await state(page)).y;
const cdp=await context.newCDPSession(page);const r=await page.locator('#field').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width*.5,y:r.y+r.height*.65,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+r.width*.3,y:r.y+r.height*.55,id:1}]});await page.waitForTimeout(250);assert.ok((await state(page)).x<stopped);assert.ok((await state(page)).y>touchY);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await page.waitForTimeout(350);const cancelled=(await state(page)).x;await page.waitForTimeout(200);assert.ok(Math.abs((await state(page)).x-cancelled)<.01);
await page.keyboard.press('p');await page.waitForTimeout(350);const frozen=(await state(page)).time;await page.waitForTimeout(300);assert.equal((await state(page)).time,frozen);await page.getByRole('button',{name:'日本語',exact:true}).click();await page.getByRole('button',{name:'再開',exact:true}).click();await page.waitForFunction(frozen=>{const game=document.querySelector('#pulse');return game.dataset.mode==='play'&&JSON.parse(game.dataset.state).time>frozen;},frozen,{timeout:3000});assert.ok((await state(page)).time>frozen);
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(350);assert.equal(await page.locator('#pulse').getAttribute('data-mode'),'pause');await page.getByRole('button',{name:'再開',exact:true}).click();await page.waitForTimeout(350);for(let i=0;i<3;i++){await page.locator('#pause').click();await page.getByRole('button',{name:'最初から再挑戦',exact:true}).dblclick();await page.waitForTimeout(350);assert.equal(await page.locator('#pulse').getAttribute('data-mode'),'play');assert.ok((await state(page)).time<1);}
await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('pocketey-pulse-drift-v1')).mute===false));assert.deepEqual(errors,[]);report.push({size,status:'passed',checks:['layout-ja-en','launch','keyboard-stop','keyboard-depth','touch-depth','touch-cancel','pause','locale-mid-pause','blur-pause','rapid-retry','sound-save'],errors});await context.close();}
for(const type of ['corrupt','blocked','webgl']){const c=await browser.newContext();const p=await c.newPage();if(type==='corrupt')await p.addInitScript(()=>localStorage.setItem('pocketey-pulse-drift-v1','{broken'));if(type==='blocked')await p.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}}));if(type==='webgl')await p.addInitScript(()=>Object.defineProperty(HTMLCanvasElement.prototype,'getContext',{value:()=>null}));await p.goto('http://localhost:4331/games/pulse-drift/?lang=en');if(type==='webgl'){await p.waitForFunction(()=>document.querySelector('#pulse').dataset.mode==='error');assert.ok((await p.locator('#overlay').textContent()).includes('3D could not start'));await p.getByRole('button',{name:'日本語',exact:true}).click();assert.ok((await p.locator('#overlay').textContent()).includes('3D表示'));}else{await p.getByRole('button',{name:'Launch',exact:true}).click();await p.waitForTimeout(200);assert.equal(await p.locator('#pulse').getAttribute('data-mode'),'play');await p.locator('#sound').click();}report.push({case:type,status:'passed'});await c.close();}
const c=await browser.newContext(),p=await c.newPage();await open(p);await p.getByRole('button',{name:'Launch',exact:true}).click();await p.evaluate(()=>document.querySelector('canvas').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.waitForFunction(()=>document.querySelector('#pulse').dataset.mode==='error');assert.ok(await p.locator('#pause').isDisabled());report.push({case:'context-loss',status:'passed'});await c.close();await fs.writeFile('test-results/shooter/ui-report.json',JSON.stringify(report,null,2));await browser.close();console.log('UI checks passed',report.length);
