import {test,expect} from '@playwright/test';import fs from 'node:fs';import {readPulse,drivePulse} from './native-driver';
const open=async(page:any,lang='en')=>{await page.goto(`/games/pulse-drift/?lang=${lang}`);await expect(page.locator('#pulse')).toHaveAttribute('data-mode','menu');};
for(const touch of[true,false])for(let stage=0;stage<3;stage++)test(`${touch?'touch':'keyboard'} stage${stage+1} clears with original shields, saves and reloads`,async({browser},info)=>{
 const context=await browser.newContext({viewport:touch?{width:390,height:844}:{width:1280,height:900},hasTouch:touch,isMobile:touch,deviceScaleFactor:1}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4322/games/pulse-drift/?lang=en');await page.getByRole('button',{name:`Stage ${stage+1}`,exact:true}).click();await expect(page.locator('#objective')).toHaveText(stage===2?'Defeat the boss before 48s':`Survive for ${stage===0?36:42}s`);await page.getByRole('button',{name:'Launch',exact:true}).click();await page.waitForFunction(()=>JSON.parse(document.querySelector<HTMLElement>('#pulse')!.dataset.state!).time>.1);
 let pausedNotice=false;const result=await drivePulse(page,touch,async observed=>{if(!touch&&stage===2&&!pausedNotice&&observed.time>=28.5&&observed.time<30){pausedNotice=true;await expect(page.locator('#arrival')).toBeVisible();await page.keyboard.press('p');await expect(page.locator('#pulse')).toHaveAttribute('data-mode','pause');await expect(page.locator('#arrival')).toBeHidden();await page.waitForTimeout(150);const t=(await readPulse(page)).time;await page.waitForTimeout(200);expect((await readPulse(page)).time).toBe(t);await page.getByRole('button',{name:'Resume',exact:true}).click();}});if(!touch&&stage===2)expect(pausedNotice).toBe(true);fs.writeFileSync(info.outputPath('route.json'),JSON.stringify({source:process.env.SOURCE_SHA,touch,stage,...result,errors},null,2));await page.screenshot({path:info.outputPath('clear.png')});expect(result.final.status).toBe('won');expect(result.final.hp).toBeGreaterThan(0);expect(result.maxTriangles).toBeLessThan(20000);if(stage===2){expect(result.arrivalSeen).toBe(true);expect(result.bossSeen).toBe(true);expect(result.beamSeen).toBe(true);expect(result.trace.some(s=>s.time>=29&&s.time<30)).toBe(true);expect(result.trace.some(s=>s.time>=30&&s.time<32&&s.enemies.some(e=>e.kind==='boss')&&s.beams.length)).toBe(true);}
 await expect(page.locator('#arrival')).toBeHidden();const saved=await page.evaluate(()=>localStorage.getItem('pocketey-pulse-drift-v1'));expect(JSON.parse(saved!).best[stage]).toBe(result.final.score);await page.reload();await expect(page.locator('#pulse')).toHaveAttribute('data-mode','menu');expect(await page.evaluate(()=>localStorage.getItem('pocketey-pulse-drift-v1'))).toBe(saved);expect(errors).toEqual([]);await context.close();
});
test('compact JA/EN objectives and menu edges stay reachable under reduced motion',async({browser},info)=>{
 for(const viewport of[{width:320,height:568},{width:844,height:390}]){const context=await browser.newContext({viewport,hasTouch:true,isMobile:true,reducedMotion:'reduce'}),page=await context.newPage();await page.goto('http://localhost:4322/games/pulse-drift/?lang=en');for(const lang of['ja','en']){await page.getByRole('button',{name:lang==='ja'?'日本語':'English',exact:true}).click();await page.getByRole('button',{name:lang==='ja'?'ステージ 3':'Stage 3',exact:true}).click();await expect(page.locator('#objective')).toContainText('48');await page.locator('#overlay h2').scrollIntoViewIfNeeded();let r=(await page.locator('#overlay h2').boundingBox())!;expect(r.y).toBeGreaterThanOrEqual(0);const launch=page.getByRole('button',{name:lang==='ja'?'出撃する':'Launch',exact:true});await launch.scrollIntoViewIfNeeded();r=(await launch.boundingBox())!;expect(r.height).toBeGreaterThanOrEqual(44);expect(r.y+r.height).toBeLessThanOrEqual(viewport.height);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`menu-${viewport.width}-${lang}.png`)});}await context.close();}
});
test('retry, pause and real context loss reset or hide the new notice and retain saved scores',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Stage 3',exact:true}).click();await page.getByRole('button',{name:'Launch',exact:true}).click();await page.waitForFunction(()=>JSON.parse(document.querySelector<HTMLElement>('#pulse')!.dataset.state!).time>.2);await page.keyboard.press('p');await expect(page.locator('#pulse')).toHaveAttribute('data-mode','pause');await page.waitForTimeout(150);const frozen=(await readPulse(page)).time;await page.waitForTimeout(300);expect((await readPulse(page)).time).toBe(frozen);await expect(page.locator('#arrival')).toBeHidden();await page.getByRole('button',{name:'Retry from start',exact:true}).click();expect((await readPulse(page)).time).toBeLessThan(1);await expect(page.locator('#arrival')).toBeHidden();const saved=await page.evaluate(()=>localStorage.getItem('pocketey-pulse-drift-v1'));await page.evaluate(()=>{const gl=document.querySelector('canvas')!.getContext('webgl2')!;gl.getExtension('WEBGL_lose_context')!.loseContext();});await expect(page.locator('#pulse')).toHaveAttribute('data-mode','error');await expect(page.locator('#arrival')).toBeHidden();expect(await page.evaluate(()=>localStorage.getItem('pocketey-pulse-drift-v1'))).toBe(saved);
});
