import {createGameAudio} from '../../audio';
import {installLocale,LANGUAGE_EVENT,tr} from '../../../lib/locale';
import {createState,step,STEP,STAGES,SAVE_KEY,cleanSave,clamp,type Save} from './model';
import {createView} from './view';
export function boot(){
 installLocale();const root=document.querySelector<HTMLElement>('#pulse')!,canvas=document.querySelector<HTMLCanvasElement>('#field')!,overlay=document.querySelector<HTMLElement>('#overlay')!;
 const el=(id:string)=>document.getElementById(id)!;let view:ReturnType<typeof createView>;
 try{view=createView(canvas);}catch{const recovery=()=>{overlay.textContent=tr('3D表示を開始できませんでした。WebGL対応ブラウザーで再度お試しください。','3D could not start. Please retry in a WebGL-enabled browser.');el('hint').textContent=tr('Pocketeyのリンクからゲーム一覧へ戻れます。','Use the Pocketey link to return to the game list.');};for(const id of ['sound','pause','menu'])el(id).hidden=true;recovery();window.addEventListener(LANGUAGE_EVENT,recovery);root.dataset.mode='error';return;}
 let storageOK=true;let save:Save;try{save=cleanSave(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'));}catch{save=cleanSave(null);storageOK=false;}
 let selected=0,s=createState(0),mode:'menu'|'play'|'pause'|'result'|'error'='menu',target={x:s.x,y:s.y},pointer:number|null=null,origin:{x:number;y:number;shipX:number;shipY:number}|null=null,keys=new Set<string>(),last=0,acc=0,frame=0;
 function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{storageOK=false;}storageNote();}
 function storageNote(){el('note').textContent=storageOK?tr('記録はこのブラウザーに保存されます。','Records stay in this browser.'):tr('保存できません。記録はこのタブでのみ保持します。','Storage unavailable. Records last for this tab only.');}
 const audio=createGameAudio('pulse',!save.mute,root,enabled=>{save.mute=!enabled;persist();labels();});audio.mount(el('sound'),pause,clearInput);
 function clearInput(){keys.clear();pointer=null;origin=null;target={x:s.x,y:s.y};}
 function button(text:string,action:()=>void,primary=false){const b=document.createElement('button');b.type='button';b.textContent=text;if(primary)b.className='primary';b.onclick=action;overlay.append(b);return b;}
 function text(title:string,description:string){overlay.replaceChildren();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=description;overlay.append(h,p);}
 function renderPanel(){
 if(mode==='play'){overlay.replaceChildren();return;}
 if(mode==='menu'){text(tr('信号の先へ。','Follow the signal.'),tr('ドラッグで自機を移動。射撃は自動。赤い弾を避け、琥珀の予告線から離れよう。白い中心が当たり判定。','Drag to move. Fire is automatic. Dodge red bullets and leave amber warning lanes. Your white core is the hitbox.'));
 const row=document.createElement('div');row.className='stage-buttons';for(let i=0;i<3;i++){const b=document.createElement('button');b.textContent=tr(`ステージ ${i+1}`,`Stage ${i+1}`);b.setAttribute('aria-pressed',String(selected===i));b.onclick=()=>{selected=i;s=createState(i);renderPanel();audio.cue('select');};row.append(b);}overlay.append(row);
 button(tr('出撃する','Launch'),start,true);const detail=document.createElement('p');detail.className='detail';detail.textContent=tr('4シールド · 矢印 / WASD · Pで一時停止 · 全3ステージ選択可能','4 shields · Arrows / WASD · P to pause · All 3 stages available');overlay.append(detail);
 }else if(mode==='pause'){text(tr('一時停止','Paused'),tr('指を離してひと休み。再開すると同じ場所から続きます。','Take a breath. Resume from the same position.'));button(tr('再開','Resume'),()=>{if(document.hidden)return;clearInput();mode='play';last=0;acc=0;renderPanel();audio.setPlaying(true);audio.cue('select');},true);button(tr('最初から再挑戦','Retry from start'),start);button(tr('ステージ選択','Stage select'),menu);
 }else if(mode==='result'){const won=s.status==='won';text(won?tr('信号を確保！','Signal secured!'):tr('信号が途切れた','Signal lost'),won?tr(`ステージ ${selected+1} クリア · スコア ${s.score}`,`Stage ${selected+1} clear · Score ${s.score}`):tr('赤い弾は小さく横に避ける。予告線は1.3秒後に発射。第3面は時間内にボスを倒そう。','Sidestep red bullets. Warning lanes fire after 1.3 seconds. Defeat the Stage 3 boss before time runs out.'));
 if(won&&selected<2)button(tr('次のステージ','Next stage'),()=>{selected++;start();},true);button(tr('もう一度','Retry'),start,!won||selected===2);button(tr('ステージ選択','Stage select'),menu);
 }else{text(tr('3D表示が停止しました','3D rendering stopped'),tr('ページを再読込して再開してください。','Reload this page to start again.'));button(tr('再読込','Reload'),()=>location.reload(),true);}
 }
 function start(){s=createState(selected);clearInput();mode='play';last=0;acc=0;renderPanel();audio.setPlaying(true,true);audio.cue('start');}
 function menu(){audio.setPlaying(false);mode='menu';clearInput();s=createState(selected);renderPanel();}
 function pause(){if(mode==='play'){mode='pause';audio.setPlaying(false);clearInput();acc=0;renderPanel();}}
 function labels(){el('sound').textContent=!audio.enabled()?tr('音 OFF','Sound OFF'):tr('音 ON','Sound ON');el('sound').setAttribute('aria-pressed',String(audio.enabled()));el('pause').textContent=tr('一時停止','Pause');el('menu').textContent=tr('ステージ選択','Stage select');el('hint').textContent=tr('ドラッグで移動 · 自動射撃 · 矢印 / WASD · Pで停止','Drag to move · Auto fire · Arrows / WASD · P to pause');storageNote();renderPanel();}
 el('sound').onclick=()=>audio.toggle();el('pause').onclick=()=>mode==='pause'?el('overlay').querySelector<HTMLButtonElement>('button')?.click():pause();el('menu').onclick=menu;
 canvas.addEventListener('pointerdown',e=>{if(mode!=='play'||pointer!==null)return;const p=view.pointer(e.clientX,e.clientY);if(!p)return;pointer=e.pointerId;origin={...p,shipX:s.x,shipY:s.y};canvas.setPointerCapture(e.pointerId);e.preventDefault();});
 canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||!origin||mode!=='play')return;const p=view.pointer(e.clientX,e.clientY);if(p)target={x:clamp(origin.shipX+p.x-origin.x,-3.8,3.8),y:clamp(origin.shipY+p.y-origin.y,.7,6.5)};e.preventDefault();});
 const release=(e:PointerEvent)=>{if(e.pointerId===pointer){pointer=null;origin=null;target={x:s.x,y:s.y};}};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);
 const movement=['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s'];window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(movement.includes(k)&&mode==='play'){keys.add(k);e.preventDefault();}if(k==='p'&&!e.repeat){if(mode==='play')pause();else if(mode==='pause')overlay.querySelector<HTMLButtonElement>('button')?.click();}});window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(keys.size===0&&pointer===null)target={x:s.x,y:s.y};});
 window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();audio.setPlaying(false);}});window.addEventListener(LANGUAGE_EVENT,labels);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();audio.setPlaying(false);mode='error';root.dataset.mode='error';clearInput();el('pause').setAttribute('disabled','');el('menu').setAttribute('disabled','');renderPanel();});
 function tick(t:number){if(mode!=='error'){const elapsed=last?Math.min((t-last)/1000,.1):0;last=t;if(mode==='play'&&!audio.settingsOpen()){acc+=elapsed;while(acc>=STEP&&mode==='play'){if(keys.size){const vx=Number(keys.has('arrowright')||keys.has('d'))-Number(keys.has('arrowleft')||keys.has('a')),vy=Number(keys.has('arrowup')||keys.has('w'))-Number(keys.has('arrowdown')||keys.has('s'));target={x:s.x+vx,y:s.y+vy};}const hp=s.hp,score=s.score,fire=s.fire,beam=s.beams.at(-1);step(s,STEP,target);acc-=STEP;if(s.hp<hp)audio.cue('damage');if(s.score>score)audio.cue('hit');if(s.fire>fire)audio.cue('shot');if(s.beams.at(-1)!==beam&&s.beams.length)audio.cue('warning');if(s.status!=='playing'){mode='result';audio.setPlaying(false);clearInput();if(s.status==='lost')audio.cue('death');if(s.status==='won'){save.best[selected]=Math.max(save.best[selected],s.score);persist();audio.cue('clear');}renderPanel();}}}view.draw(s);
 const boss=s.enemies.find(e=>e.kind==='boss');el('boss-health').hidden=!boss||mode!=='play';if(boss){el('boss-label').textContent=tr(`中枢シールド ${boss.hp} / 32`,`Core shields ${boss.hp} / 32`);(el('boss-meter') as HTMLProgressElement).value=boss.hp;}
 el('stage-label').textContent=tr(STAGES[selected].ja,STAGES[selected].en);el('health').textContent=`${'◆'.repeat(s.hp)}${'◇'.repeat(4-s.hp)}`;el('health').setAttribute('aria-label',tr(`シールド ${s.hp} / 4`,`Shields ${s.hp} of 4`));el('clock').textContent=`${Math.max(0,Math.ceil(STAGES[selected].duration-s.time))}s`;el('score').textContent=tr(`スコア ${s.score} · 最高 ${save.best[selected]}`,`Score ${s.score} · Best ${save.best[selected]}`);el('warning').textContent=mode==='play'&&s.beams.some(b=>b.age<1.3)?tr('予告線から離れて！','Leave the warning lane!'):'';el('pause').toggleAttribute('disabled',mode!=='play'&&mode!=='pause');
 if(frame++%6===0){root.dataset.mode=mode;root.dataset.state=JSON.stringify({stage:s.stage,time:s.time,x:s.x,y:s.y,hp:s.hp,status:s.status,score:s.score,enemies:s.enemies,bullets:s.bullets,beams:s.beams,screen:view.project(s.x,s.y),limits:[view.project(-3.8,.7),view.project(3.8,6.5)],render:view.stats()});}}
 requestAnimationFrame(tick);}
 labels();requestAnimationFrame(tick);window.addEventListener('pagehide',e=>{pause();if(!e.persisted)view.dispose();});
}
